### ISSUE TITLE
z-order of elements

### ISSUE THREAD

**Issue by jfgilliam** [ibm-js/dgauges#6]
I took the dgauges/components/default/CurcularLinearGauge and copied it. Added another CircularScale using addElements and a different name. It rendered it fine, but it is appearing on top of the indicator (needle). I called addElement right after the "scale" element and before the indicator was added. I would have expected the z-order to place it behind the indicator.

Along the same line as this, the text indicator appears on top of the needle indicator and I would like it to appear below it. I tried changing the order in which I called addElement, but that didn't help. 

Is there a way to render the elements in the order they are added, such that the z-order is correct? BTW using 1.9.2 of dojo.

**Comment by dmandrioli** [comment]
Elements (added by addElement method) should be correctly z-ordered. Could you provide your sample (or better, a jsFiddle) for investigation?

**Comment by jfgilliam** [comment]
OK, here you go.

http://jsfiddle.net/s5Kpd/11/

I don' t know why I can get the black circles scale to center the same as the other one, but you can see the problem anyway if you move the needle over the black circle or over the value text, the needle is behind them. I want the needle on top.

##  

Jeff

**Comment by dmandrioli** [comment]
Hi Jeff,

Here is a fork of your fiddle that should solve your problems. I've done the following modifications:
1. Correct the typos: "orginX/Y" => "originX/Y"
2. Move the addElement("scale", scale) after your addition. The needle is part of the scale, so you need to add the default scale after your scale.

http://jsfiddle.net/dmandrioli/cQ7VR/

Another point you may want to know: The addIndicator() method has a third boolean argument to control if the indicator is on top or below its scale.

**Comment by jfgilliam** [comment]
Thanks for your response. For my particular use case, this is going to work for me. But it seems that if I wanted this scale to be between the main scale and it's indicator because it may overlay it, it would not be possible. Maybe the indicator creation should be decoupled while elements are being added, then link them together.

##  

Jeff
